//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoForum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNodeInfo
    {
        public string UserId { get; set; }
        public string DirName { get; set; }
        public long Port { get; set; }
        public long RPCPort { get; set; }
        public int PeerId { get; set; }
        public string Handshake { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
